import { Component } from '@angular/core';

@Component({
  selector: 'app-view-all',
  templateUrl: './view-all.component.html',
  styleUrls: ['./view-all.component.css']
})
export class ViewAllComponent {

  data:any=[
    {
      src:"https://cdn.windowsreport.com/wp-content/uploads/2020/04/Book-Cover-1200x900.jpg",
      BookName:"Book1",
      Author:"Author1",
      Publisher:"Publisher1",
      Language:"Language1",
      Distrbutor:"Distrbutor1",
      ReleaseYear:"ReleaseYear1",
      Price:"Price1"
    },
    {
      src:"https://cdn.windowsreport.com/wp-content/uploads/2020/04/Book-Cover-1200x900.jpg",
      BookName:"Book2",
      Author:"Author2",
      Publisher:"Publisher2",
      Language:"Language2",
      Distrbutor:"Distrbutor2",
      ReleaseYear:"ReleaseYear2",
      Price:"Price2"
    },
    {
      src:"https://cdn.windowsreport.com/wp-content/uploads/2020/04/Book-Cover-1200x900.jpg",
      BookName:"Book3",
      Author:"Author3",
      Publisher:"Publisher3",
      Language:"Language3",
      Distrbutor:"Distrbutor3",
      ReleaseYear:"ReleaseYear3",
      Price:"Price3"
    },
    {
      src:"https://cdn.windowsreport.com/wp-content/uploads/2020/04/Book-Cover-1200x900.jpg",
      BookName:"Book4",
      Author:"Author4",
      Publisher:"Publisher4",
      Language:"Language4",
      Distrbutor:"Distrbutor4",
      ReleaseYear:"ReleaseYear4",
      Price:"Price4"
    },
    {
      src:"https://cdn.windowsreport.com/wp-content/uploads/2020/04/Book-Cover-1200x900.jpg",
      BookName:"Book5",
      Author:"Author5",
      Publisher:"Publisher5",
      Language:"Language5",
      Distrbutor:"Distrbutor5",
      ReleaseYear:"ReleaseYear5",
      Price:"Price5"
    },
    {
      src:"https://cdn.windowsreport.com/wp-content/uploads/2020/04/Book-Cover-1200x900.jpg",
      BookName:"Book6",
      Author:"Author6",
      Publisher:"Publisher6",
      Language:"Language6",
      Distrbutor:"Distrbutor6",
      ReleaseYear:"ReleaseYear6",
      Price:"Price6"
    },
    {
      src:"https://cdn.windowsreport.com/wp-content/uploads/2020/04/Book-Cover-1200x900.jpg",
      BookName:"Book7",
      Author:"Author7",
      Publisher:"Publisher7",
      Language:"Language7",
      Distrbutor:"Distrbutor7",
      ReleaseYear:"ReleaseYear7",
      Price:"Price7"
    },
    {
      src:"https://cdn.windowsreport.com/wp-content/uploads/2020/04/Book-Cover-1200x900.jpg",
      BookName:"Book8",
      Author:"Author8",
      Publisher:"Publisher8",
      Language:"Language8",
      Distrbutor:"Distrbutor8",
      ReleaseYear:"ReleaseYear8",
      Price:"Price8"
    },
    {
      src:"https://cdn.windowsreport.com/wp-content/uploads/2020/04/Book-Cover-1200x900.jpg",
      BookName:"Book9",
      Author:"Author9",
      Publisher:"Publisher9",
      Language:"Language9",
      Distrbutor:"Distrbutor9",
      ReleaseYear:"ReleaseYear9",
      Price:"Price9"
    },
    {
      src:"https://cdn.windowsreport.com/wp-content/uploads/2020/04/Book-Cover-1200x900.jpg",
      BookName:"Book10",
      Author:"Author10",
      Publisher:"Publisher10",
      Language:"Language10",
      Distrbutor:"Distrbutor10",
      ReleaseYear:"ReleaseYear10",
      Price:"Price10"
    },
    {
      src:"https://cdn.windowsreport.com/wp-content/uploads/2020/04/Book-Cover-1200x900.jpg",
      BookName:"Book11",
      Author:"Author11",
      Publisher:"Publisher11",
      Language:"Language11",
      Distrbutor:"Distrbutor11",
      ReleaseYear:"ReleaseYear11",
      Price:"Price11"
    },
    {
      src:"https://cdn.windowsreport.com/wp-content/uploads/2020/04/Book-Cover-1200x900.jpg",
      BookName:"Book12",
      Author:"Author12",
      Publisher:"Publisher12",
      Language:"Language12",
      Distrbutor:"Distrbutor12",
      ReleaseYear:"ReleaseYear12",
      Price:"Price2"
    }

  ]

}
